### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/Sora-iOS#168]
<br/>

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-725

**Comment by Tieumsan** [comment]
**Design review**

https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=5235-14962&mode=design&t=9NyGmfOmesd4PDHf-0

**Comment by Trezeguet1** [comment]
1. Trim separators on the Account options screen

<img width="339" alt="image" src="https://github.com/sora-xor/sora-ios/assets/51509139/e768ba8c-74e7-4d4b-a396-dfc1ddda06fa">

2. Make a red gradient for the nav bar buttons as in the design and as on Android

![telegram-cloud-photo-size-2-5372821650426417801-y](https://github.com/sora-xor/sora-ios/assets/51509139/fb771001-2372-4906-a983-445ad9e2febc)

3. All buttons should be purple and bold (instead of white and non-bold)

Here it’s bold
![telegram-cloud-photo-size-4-5917882115872113093-y](https://github.com/sora-xor/sora-ios/assets/51509139/f58c4946-33fa-42ef-a573-9474b525763f)

Here it’s bold and white
![telegram-cloud-photo-size-4-5917882115872113094-y](https://github.com/sora-xor/sora-ios/assets/51509139/856067eb-7e8c-4d48-a47a-f435d62d9457)

Bold and grey
![telegram-cloud-photo-size-4-5917882115872113095-y](https://github.com/sora-xor/sora-ios/assets/51509139/f06aa04b-ed48-4c6d-b8d9-8fa824e2de1f)

Bold and white
![telegram-cloud-photo-size-4-5917882115872113096-y](https://github.com/sora-xor/sora-ios/assets/51509139/3fca6fbb-9e43-4bb5-ba44-5d5986e0f6a7)

Bold and purple
![telegram-cloud-photo-size-4-5917882115872113097-y](https://github.com/sora-xor/sora-ios/assets/51509139/6b6d119c-46b5-42a1-afce-3d41d53766da)

**Comment by Trezeguet1** [comment]
Verified on Verified on 1.0 (255) version.

<img width="408" alt="Screenshot 2023-11-16 at 13 02 55" src="https://github.com/sora-xor/sora-ios/assets/51509139/f5c34162-0982-4fd5-8c36-5d00788fc57a">

<img width="414" alt="Screenshot 2023-11-16 at 13 03 01" src="https://github.com/sora-xor/sora-ios/assets/51509139/2ebc2806-c4e8-4c1a-bb99-b3dbfa649b55">
