### ISSUE TITLE
[Bug]: price change percent on Explore tab should be aligned left in Arabic and Hebrew

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#180]
### Preconditions

Arabic or Hebrew languages is set up

### Steps to reproduce

Open Explore page

### Actual behavior

Percents in Currencies card are aligned badly. Also % sign is on the right.

% sign in Polkaswap pools is in the right (328% APY)

### Expected behavior

It should be aligned left. $ sign should be on the 1st place

The order should be: %328 APY

### Environment

{"label"=>"Development"}

### Additional context

![photo_2023-10-16 14 13 18](https://github.com/sora-xor/sora-ios/assets/7602319/ab5771b2-bc72-4a78-b071-73efe7c7162a)

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 ((219)) for iOS version.

Move the numbers next to the asset icons to the right so that they no longer blend together.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGx0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb3cc409104ecdbcb5dc307267cc4bdb243cafeb/image.png)

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (238) for iOS version.

![telegram-cloud-photo-size-2-5332618505972993416-y](https://github.com/sora-xor/sora-ios/assets/51509139/b27e8133-1b2c-4035-97fe-c156bb807514)
