### ISSUE TITLE
[Tech]: Improve responsiveness of token selection list

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#190]
### Problem statement

iOS and iPhone allows to have high performance UI. 

When we push the select token field on swap or LP, it takes about 1 second to open the list. It should be instant.

### Definition of Done

Opening the list of token selection is instant

- Swap
- Provide liquidity

**Comment by Trezeguet1** [comment]
Verified on Soralution 3.7.0 (22) version.

The token selection list opens instantly.

The changes were made as part of the task when we increased the speed of opening assets due to asynchronous loading from subqueries and added shimmers to Recent activity.

![telegram-cloud-photo-size-2-5366255886676381868-y](https://github.com/sora-xor/sora-ios/assets/51509139/ee9136c3-01e0-4762-ba7a-f4d0ac145627)
