### ISSUE TITLE
[Bug]: iOS - Design review. Night Mode.

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#195]
### Useful links
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=5235-14962&mode=design&t=9NyGmfOmesd4PDHf-0

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (219) for iOS version.

Most likely, there are still no changes to the dark mod in the development, since it is clear that the background is purple. I also changed the mod systemically, but it did not affect the mod in the app.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenRuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32bd834fbefcc79e5916dac2fd764fa427b59389/telegram-cloud-photo-size-2-5314346675713724566-y.jpg)


Please update the palette in the layouts to the one relevant for the dark mod.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenhuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89239243c77676fa3f0f0c12b3085cf031eae952/telegram-cloud-photo-size-2-5312003667974541945-y.jpg)

**Comment by Trezeguet1** [comment]
We need to fix dark theme for SORA Card flow.

![telegram-cloud-photo-size-2-5357372348120026738-y](https://github.com/sora-xor/sora-ios/assets/51509139/30125d09-17d2-4908-9306-cfaa2591d876)

![telegram-cloud-photo-size-2-5357372348120026739-y](https://github.com/sora-xor/sora-ios/assets/51509139/a48213b2-b9b8-42a7-b47f-540ebe7150f8)

![telegram-cloud-photo-size-2-5357372348120026740-y](https://github.com/sora-xor/sora-ios/assets/51509139/b1277633-188b-4c8b-b2af-f8aa308dd421)

![telegram-cloud-photo-size-2-5357372348120026741-y](https://github.com/sora-xor/sora-ios/assets/51509139/2d680b98-28b5-4c5f-98ba-f7db7da034fd)

![telegram-cloud-photo-size-2-5357372348120026742-y](https://github.com/sora-xor/sora-ios/assets/51509139/93b5edb5-ad25-45c1-ad3b-fe138c541ac9)

![telegram-cloud-photo-size-2-5357372348120026743-y](https://github.com/sora-xor/sora-ios/assets/51509139/2b57138b-232b-40d3-9377-0ecf3e77c0ae)

![telegram-cloud-photo-size-2-5357372348120026744-y](https://github.com/sora-xor/sora-ios/assets/51509139/faa2ed81-8f84-4262-ab2d-05c8e22831ad)

![telegram-cloud-photo-size-2-5357372348120026751-y](https://github.com/sora-xor/sora-ios/assets/51509139/2dd8be51-5e64-4577-8a24-4f0a9e0c1acb)

**Comment by Trezeguet1** [comment]
Verified on 1.0. (255) version.
